[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure text files are served with correct MIME type
[[headers]]
  for = "/*.txt"
  [headers.values]
    Content-Type = "text/plain"